In [14]:
import numpy as np
import pandas as pd

In [2]:
liste = [1,2,3,4,5]

In [3]:
type(liste)

list

In [4]:
liste2 = np.array([1,2,3,4,5])

In [6]:
type(liste2)

numpy.ndarray

In [ ]:
# [[1, 2, 3, 4, 5],[4,5,6]]

In [10]:
liste3 = np.array([[1, 2, 3,],[4,5,6]])

In [12]:
colonlar= ["yaş","maaş","gün"]

In [15]:
pd.DataFrame(data=liste3,columns=colonlar)

yaş  maaş  gün
0    1     2    3
1    4     5    6

In [18]:
random_array = np.random.randint(0,10,size=(3,3))
print(random_array)


[[5 1 7]
 [0 9 3]
 [0 6 6]]


In [19]:
arr = np.array([1,2,3,4])
np.sum(arr)

np.int64(10)

In [20]:
np.mean(arr)

np.float64(2.5)